### ISSUE TITLE
Possible error with carriage returns in body

### ISSUE THREAD

**Issue by ebram-va** [lindluni/warden-invite#2]
I had an issue that needed to be edited and re-submitted before running through the invite process again.  I haven't been able to test and confirm, but somehow it seems that carriage returns were introduced during the editing process.   When I looked at jobs that succeeded versus mine, I noticed none of the other ones had carriage returns.  I only edited in the GitHub Issues editor, but I wonder if that act alone introduced the carriage returns.  
https://github.com/lindluni/warden-invite/blob/main/index.js#L37-L42

This is the action output error:
```
Run lindluni/warden-invite@main
(node:1555) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
    at /home/runner/work/_actions/lindluni/warden-invite/main/dist/index.js:2:121816
    at /home/runner/work/_actions/lindluni/warden-invite/main/dist/index.js:2:124125
    at /home/runner/work/_actions/lindluni/warden-invite/main/dist/index.js:2:124129
    at Object.<anonymous> (/home/runner/work/_actions/lindluni/warden-invite/main/dist/index.js:2:124133)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
(node:1555) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1555) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The [sanitized] body from my edit came out as seen in the GitHub Actions log as:

body: "### Acknowledge Instructions\r\n\r\n- [X] I acknowledge that I have read the above instructions and will provide the user I am requesting to add with instructions on how to accept their invite via email or by visiting the [NAME](URL) page\r\n\r\n\r\n### Full Name\r\n\r\nX Service Account\r\n\r\n### Email\r\n\r\nEMAIL@EMAIL.COM\r\n\r\n### GitHub Username\r\n\r\n@test-svc\r\n\r\n### PM/COR Email Address\r\n\r\nEMAIL@EMAIL.COM\r\n\r\n### PM/COR GitHub Username\r\n\r\n@pm\r\n\r\n### Assigned Contract\r\n\r\nTEST"

**Comment by lindluni** [comment]
Hey @ebram-va, that is the issue 😭 

When you edit an issue GitHub replaces all `\n` characters with `\r\n`, I was aware of this, but hadn't gotten around to fixing it, your best bet in that instance is to just create a new issue, until I can fix it. We are also looking to just write a standalone replacement for this Action as an app, so we can actually validate data on submit and reduce friction.

**Comment by ebram-va** [comment]
Cool!  I'm not sure what your build process is, if you want PRs to include a pre-built `dist/index.js` or not, but I did create my own fork and test issue repo to test out the fix:

Fix:  https://github.com/ebram-va/warden-invite/blob/main/index.js#L37
Output to show start of flow working properly:  https://github.com/ebram-va/test-warden-invite/runs/4312904221?check_suite_focus=true

Forked repo:  https://github.com/ebram-va/warden-invite
Test calling repo: https://github.com/ebram-va/test-warden-invite/blob/main/.github/workflows/test.yml
Test Issue:  https://github.com/ebram-va/test-warden-invite/issues/3

If you'd like me to put in a PR, just let me know if you want just the `./index.js` or `./index.js` _and_ `./dist/index.js`.

**Comment by ebram-va** [comment]
@lindluni ^

**Comment by lindluni** [comment]
Hey @ebram-va 

You only need to edit `index.js`, `ncc` builds the `dist`

You can open a pull request, this action is now built with `ncc` you will need to do a `git fetch && git rebase origin/main`
and then you can do an `npm run build` which will generate the `dist` directory for you

**Comment by lindluni** [comment]
If you open a PR, I can always commit on top of it to do the rebase and add the dist dir

**Comment by ebram-va** [comment]
Got it, no problem!  The confusion for me before was that `dist` was being generated as minified, and I felt like it was a security risk that someone other than you or your automation was generating and committing it.  Now that it appears to not be minified, it's easy for you to verify that the `dist/index.js` file is valid.  I put in a PR, thanks!
